### ISSUE TITLE
Murder Mystery

### ISSUE THREAD

**Issue by TrustedMercury** [Derkades/Minigames#130]
* Needs atleast 4 people playing. 
* One among all the players will be a murderer. 
* The murderer has to kill the others in a certain time slot. 
* The map should be big but sheltered like the lobby, lots of parkour and other things like mazes where players can hide and run from the murderer. 
* Could also make it such that there is a cop who tried to guess the murderer._

**Comment by Derkades** [comment]
Added! I think the map we built is exactly what you had in mind (except for the parkour part).
