### ISSUE TITLE
[UPDATE] Break The Block - MINIGAMES

### ISSUE THREAD

**Issue by TrustedMercury** [Derkades/Minigames#133]
Add new maps for this minigame. Playing on the same map isn't really fun after one point.

Make the elytra jumps easier in the first map. [PROTOTYPE]

Reduce the number of PvP blocks.

**Comment by Derkades** [comment]
>Add new maps for this minigame
Will happen in the future

> Make the elytra jumps easier in the first map. [PROTOTYPE]
Done a while ago

> Reduce the number of PvP blocks.
No
