### ISSUE TITLE
Race - Minigame

### ISSUE THREAD

**Issue by TrustedMercury** [Derkades/Minigames#217]
Just a simple race game. The first person to reach some place wins. The map could have some cool stuff like some parkour, slimeblocks, small pvp sections, etc. Could also add a boat race or some parts in the normal one where you go swimming or boating.

**Comment by TrustedMercury** [comment]
You can also make a boat race.

**Comment by Derkades** [comment]
This seems very similar to break the block or #25. If it is, please close the issue and comment on #25 or create a new issue for btb suggestions
