### ISSUE TITLE
Speakers playing lobby music, located at every speaker box

### ISSUE THREAD

**Issue by patchtv** [Derkades/Minigames#96]
this also for the hub map.

**Comment by Derkades** [comment]
So make a dedicated plugin for this feature?

**Comment by patchtv** [comment]
preferrably, yes.

**Comment by patchtv** [comment]
standalone LobbyMusicX needs configurable: 
- `loop-timer` (time in s, to loop the playsound function)
- `tracks` (list/array)
- `speaker-locations` (list/array)
- `sound-source` (being able to set it to play through minecraft's master audio, voice/speech, player, noteblock, music audio etc.)
